inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1
